#!/bin/zsh

# faceted search
show=0
if [[ "$1" == "-S" || "$1" == "--show-matches" ]]
then
	show=1
	shift
fi

if [ $# -eq 0 ]
then
	echo >&2 "$0: at least one pattern required"
	exit 1
fi

if [[ ${@[$#]} == -* ]]
then
	echo >&2 "$0: last argument must be a pattern, not a flag"
	exit 1
fi

function extract_flags()
{
	local start=$1
	shift
	local v=("$@")
	local next=$start

	while [[ $next < ${#v[@]} ]]
	do
		if [[ "${v[@]:$next:1}" != -* ]]
		then
			break
		fi
		echo "${v[@]:$next:1}"
		next=$((next + 1))
	done

	return $((next - count))
}

# TODO - fix to run with "show", for now, suppress
function run_egrep()
{
	local pat=$1
	local last=$2
	local show=$3
	shift 3
	local opts="$@"
	local zero_opt=""
	# TODO - remove suppression
	show=0
	if (( $last == 0 ))
	then
		zero_opt=--null
	fi
	if (( $show == 1 )) 
	then
		file_opt=-H
	else
		file_opt=--files-with-matches
	fi

	xargs -0 egrep \
		--binary-files=without-match \
		$zero_opt \
		$file_opt \
		$(echo $opts) \
		"$pat"
	return $?
}

args=($@)
arg_count=${#args[@]}

arg_idx=0
egrep_options=$(extract_flags $arg_idx ${args[@]})
arg_idx=$?
all_options=($egrep_options)

pat="${args[@]:$arg_idx:1}"
# TODO - remove all_pats when show is supported
all_pats=("$pat")

files=$(
	find . \
		-type d \( \
			-name node_modules \
			-o -name dist \
			-o -name '.?*' \
		\) \
		-prune \
		-o \
		\( \
			-type f \
			! -name '.*' \
			! -name 'package-lock.json' \
			! -name 'yarn.lock' \
			! -name '*.log' \
		\) \
		-print0 |
		run_egrep "$pat" $((arg_idx == arg_count - 1)) $show $egrep_options
)

if [ $? -ne 0 ]
then
	# egrep returned nothing - no results
	exit 1
fi

arg_idx=$((arg_idx + 1))

# Now iterate per pattern
while (( $arg_idx < $arg_count ))
do
		egrep_options=$(extract_flags $arg_idx ${args[@]})
		arg_idx=$?

		all_options+=($egrep_options)
		pat="${args[@]:$arg_idx:1}"
		all_pats+=("$pat")
		
		files=$(echo -n $files | run_egrep "$pat" $((arg_idx == arg_count - 1)) $show $egrep_options)

		if [ $? -ne 0 ]
		then
			# egrep returned nothing - no results
			exit 1
		fi
		arg_idx=$((arg_idx + 1))
done


# TODO - remove this block when 'show' is supported in 'run_egrep'
if [[ $show == 1 ]]
then 
	export IFS=$'\n'
	for (( i=0; i<${#all_pats[@]}; i++ ))
	do
		pat=${all_pats[@]:$i:1}
		egrep_options=${all_options[@]:$i:1}
		egrep \
			-H \
			$(echo $egrep_options) \
			"$pat" \
			$(echo $files)
	done | sort | uniq
else
	echo $files
fi
exit 0
